/**
 * The four basemaps Meridian can draw, all keyless.
 *
 *  - **`hybrid`** (the default) — satellite imagery with roads, borders and place
 *    names drawn on top. The generalist: it reads the same in Bavaria, Bengal or
 *    the middle of an ocean, needs no local knowledge to interpret, and shows the
 *    actual ground you journaled on rather than a cartographer's abstraction of it.
 *  - **`satellite`** — the same imagery with nothing over it.
 *  - **`parchment`** — Meridian's own vector cartography, coloured from the app's
 *    Cartographer's Parchment palette so the map reads as part of the app rather
 *    than a window onto someone else's website. Follows light/dark.
 *  - **`osm`** — plain OpenStreetMap raster tiles. The most forgiving option
 *    offline and on a weak device, and the automatic fallback.
 *
 * **Where the pixels come from.** Vector tiles (parchment, and the label overlay
 * in hybrid) come from **OpenFreeMap** (https://openfreemap.org) — OpenStreetMap
 * data in the OpenMapTiles schema, no API key, no account, no quota. Imagery comes
 * from **Esri's World Imagery** service, likewise keyless. That constraint is not
 * incidental: Meridian has no signup and holds no secrets, so anything needing a
 * token (Google's tiles among them — their terms also forbid raw tile access
 * outside their own APIs) was never an option.
 *
 * Two honest limitations:
 *
 *  1. **Labels use Noto Sans, not the app's Merriweather.** MapLibre renders text
 *     from pre-generated glyph atlases (`.pbf`), not from browser webfonts, so a
 *     font is only usable if someone serves its glyphs. OpenFreeMap serves the Noto
 *     stacks. Noto Sans has the side benefit of full Bengali coverage, which the
 *     app needs anyway.
 *  2. **Vector tiles need the network on first view.** Raster tiles — OSM *and*
 *     imagery — are cached by the service worker (see `vite.config.ts`), and the
 *     offline region download stores OSM raster tiles. So `'osm'` remains a
 *     first-class choice, not a legacy fallback: it is the most robust option
 *     offline. The map falls back to it automatically if a vector source fails,
 *     and hybrid degrades to plain `satellite` if only its labels fail.
 *
 * Every style is generated by a pure function so it can be unit-tested, and so the
 * dark parchment variant is genuinely the same style with a different palette
 * rather than a second copy that drifts.
 */
import type { StyleSpecification } from 'maplibre-gl';
import type { MapStyleId } from '../../store/settings';

const OPENFREEMAP_TILES = 'https://tiles.openfreemap.org/planet';
const OPENFREEMAP_GLYPHS = 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf';
const OSM_RASTER = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png';
/** Esri World Imagery. Note the tile path is `{z}/{y}/{x}` — row before column. */
const ESRI_IMAGERY =
  'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}';

const ATTRIBUTION = '&copy; OpenStreetMap contributors';
const IMAGERY_ATTRIBUTION = 'Imagery &copy; Esri, Maxar, Earthstar Geographics';

/**
 * Deepest zoom the imagery service has tiles for. Declared on the source so
 * MapLibre over-zooms the z19 tile instead of requesting z20+ and collecting a
 * stream of 404s (which would look identical to a dead network).
 */
const IMAGERY_MAX_ZOOM = 19;

/** The colours any label layer needs, whatever it is drawn over. */
interface LabelColours {
  label: string;
  labelHalo: string;
  waterLabel: string;
}

/** Every colour the vector style uses, for one theme. */
interface Palette extends LabelColours {
  /** Bare ground — the map's equivalent of the app's parchment. */
  land: string;
  water: string;
  waterLine: string;
  /** Woods, parks, grass. */
  green: string;
  /** Sand, beaches, bare rock. */
  sand: string;
  /** Built-up area wash, under the individual buildings. */
  urban: string;
  building: string;
  buildingOutline: string;
  /** Motorways and trunk roads — the app's accent, so the network reads warm. */
  majorRoad: string;
  majorRoadCasing: string;
  minorRoad: string;
  minorRoadCasing: string;
  path: string;
  rail: string;
  boundary: string;
}

/**
 * Light: warm cream ground, slate ink labels, terracotta arteries. The greens and
 * blues are heavily desaturated so the terracotta stays the only saturated colour
 * on the map, the way an old survey sheet works.
 */
const LIGHT: Palette = {
  land: '#FDFBF7',
  water: '#C7D5DD',
  waterLine: '#B4C6D0',
  green: '#DFE7DB',
  sand: '#F1E8D6',
  urban: '#F5F1E8',
  building: '#EAE3D6',
  buildingOutline: '#DDD4C3',
  majorRoad: '#D08A78',
  majorRoadCasing: '#F6EDE6',
  minorRoad: '#FFFFFF',
  minorRoadCasing: '#E4DBC9',
  path: '#C8BCA6',
  rail: '#BBAF9C',
  boundary: '#A99C88',
  label: '#2C3E50',
  labelHalo: '#FDFBF7',
  waterLabel: '#5B7383',
};

/**
 * Dark: the same map at night. Kept blue-slate rather than pure black so it sits
 * with the app's dark theme (`#14181E` background, `#242C35` surfaces) instead of
 * looking like a hole in the page.
 */
const DARK: Palette = {
  land: '#181D24',
  water: '#10161C',
  waterLine: '#1C2530',
  green: '#1B2422',
  sand: '#242219',
  urban: '#1D232B',
  building: '#232A33',
  buildingOutline: '#2C343E',
  majorRoad: '#8C4536',
  majorRoadCasing: '#20262E',
  minorRoad: '#2A323C',
  minorRoadCasing: '#20262E',
  path: '#3A424D',
  rail: '#3D4550',
  boundary: '#4A5361',
  label: '#D8DEE6',
  labelHalo: '#12171D',
  waterLabel: '#7A8EA0',
};

/**
 * Label colours for text drawn over satellite imagery: white type with a dark
 * halo, the only combination that stays readable over a snowfield and a forest in
 * the same view.
 */
const IMAGERY: LabelColours = {
  label: '#FFFFFF',
  labelHalo: '#12171D',
  waterLabel: '#CFE3F2',
};

/** Interpolate a line width across zooms — MapLibre's stops, spelled out once. */
function widthByZoom(stops: Array<[number, number]>) {
  return {
    'base': 1.4,
    'stops': stops,
  };
}

/**
 * The label layers, shared by the parchment style and the hybrid overlay — the
 * same cartography of names in both, so a place that is labelled on one basemap is
 * labelled on the other. Always appended last, so nothing paints over text.
 *
 * `haloScale` widens the halo for imagery, where text has to survive an arbitrary
 * photographic background rather than a flat fill.
 */
function labelLayers(c: LabelColours, haloScale = 1): StyleSpecification['layers'] {
  return [
    {
      id: 'label-water',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'water_name',
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Italic'],
        'text-size': 12,
        'text-max-width': 7,
      },
      paint: {
        'text-color': c.waterLabel,
        'text-halo-color': c.labelHalo,
        'text-halo-width': 1.1 * haloScale,
      },
    },
    {
      id: 'label-road',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 14,
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': 11,
        'symbol-placement': 'line',
        'text-rotation-alignment': 'map',
      },
      paint: {
        'text-color': c.label,
        'text-opacity': 0.75,
        'text-halo-color': c.labelHalo,
        'text-halo-width': 1.4 * haloScale,
      },
    },
    {
      id: 'label-place-small',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['in', 'class', 'village', 'suburb', 'neighbourhood', 'hamlet'],
      minzoom: 11,
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': 11,
        'text-max-width': 8,
      },
      paint: {
        'text-color': c.label,
        'text-opacity': 0.8,
        'text-halo-color': c.labelHalo,
        'text-halo-width': 1.4 * haloScale,
      },
    },
    {
      id: 'label-place-town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['in', 'class', 'city', 'town'],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Bold'],
        'text-size': { 'stops': [[4, 11], [8, 13], [12, 17]] },
        'text-max-width': 8,
        // A survey-sheet touch: settlement names slightly letter-spaced.
        'text-letter-spacing': 0.05,
      },
      paint: {
        'text-color': c.label,
        'text-halo-color': c.labelHalo,
        'text-halo-width': 1.6 * haloScale,
      },
    },
    {
      id: 'label-country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', 'class', 'country'],
      maxzoom: 8,
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Bold'],
        'text-size': { 'stops': [[2, 10], [6, 15]] },
        'text-letter-spacing': 0.18,
        'text-transform': 'uppercase',
        'text-max-width': 7,
      },
      paint: {
        'text-color': c.label,
        'text-opacity': 0.7,
        'text-halo-color': c.labelHalo,
        'text-halo-width': 1.6 * haloScale,
      },
    },
  ] as StyleSpecification['layers'];
}

/**
 * The plain OpenStreetMap raster style. Kept as its own function because it is
 * still the right answer offline (the service worker and the offline tile cache
 * both cache raster tiles) and on very weak GPUs.
 */
export function rasterStyle(): StyleSpecification {
  return {
    version: 8,
    sources: {
      osm: {
        type: 'raster',
        tiles: [OSM_RASTER],
        tileSize: 256,
        attribution: ATTRIBUTION,
      },
    },
    layers: [{ id: 'osm', type: 'raster', source: 'osm' }],
  };
}

/**
 * Build the parchment vector style for a theme.
 *
 * Layer order is deliberate and matters: background → land cover → water →
 * buildings → road casings → road fills → rail → boundaries → labels. Casings
 * before fills is what gives roads their outlined look; labels last so nothing
 * ever draws over text.
 */
export function parchmentStyle(dark: boolean): StyleSpecification {
  const c = dark ? DARK : LIGHT;

  return {
    version: 8,
    name: `Meridian — Cartographer's Parchment${dark ? ' (night)' : ''}`,
    glyphs: OPENFREEMAP_GLYPHS,
    sources: {
      openmaptiles: {
        type: 'vector',
        url: OPENFREEMAP_TILES,
        attribution: ATTRIBUTION,
      },
    },
    layers: [
      { id: 'background', type: 'background', paint: { 'background-color': c.land } },

      // --- Land cover ---------------------------------------------------------
      {
        id: 'landuse-urban',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landuse',
        filter: ['in', 'class', 'residential', 'suburb', 'quarter', 'neighbourhood'],
        paint: { 'fill-color': c.urban },
      },
      {
        id: 'landcover-green',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landcover',
        filter: ['in', 'class', 'wood', 'grass', 'farmland'],
        paint: { 'fill-color': c.green, 'fill-opacity': 0.85 },
      },
      {
        id: 'landcover-sand',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landcover',
        filter: ['in', 'class', 'sand', 'rock'],
        paint: { 'fill-color': c.sand },
      },
      {
        id: 'park',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'park',
        paint: { 'fill-color': c.green, 'fill-opacity': 0.6 },
      },

      // --- Water --------------------------------------------------------------
      {
        id: 'water',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'water',
        paint: { 'fill-color': c.water },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'waterway',
        paint: {
          'line-color': c.waterLine,
          'line-width': widthByZoom([
            [9, 0.6],
            [14, 1.6],
            [18, 4],
          ]),
        },
      },

      // --- Buildings ----------------------------------------------------------
      {
        id: 'building',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'building',
        minzoom: 13,
        paint: {
          'fill-color': c.building,
          'fill-outline-color': c.buildingOutline,
          // Fade in rather than popping into existence at z13.
          'fill-opacity': { 'stops': [[13, 0], [15, 1]] },
        },
      },

      // --- Roads: casings first, then fills ----------------------------------
      {
        id: 'road-minor-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'minor', 'service', 'tertiary'],
        minzoom: 12,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': c.minorRoadCasing,
          'line-width': widthByZoom([
            [12, 1.4],
            [16, 5],
            [20, 20],
          ]),
        },
      },
      {
        id: 'road-major-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'motorway', 'trunk', 'primary', 'secondary'],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': c.majorRoadCasing,
          'line-width': widthByZoom([
            [7, 1.6],
            [12, 4.5],
            [16, 11],
            [20, 32],
          ]),
        },
      },
      {
        id: 'road-path',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'path', 'track'],
        minzoom: 13,
        layout: { 'line-cap': 'round' },
        paint: {
          'line-color': c.path,
          'line-dasharray': [2, 2],
          'line-width': widthByZoom([
            [13, 0.7],
            [18, 2.4],
          ]),
        },
      },
      {
        id: 'road-minor',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'minor', 'service', 'tertiary'],
        minzoom: 12,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': c.minorRoad,
          'line-width': widthByZoom([
            [12, 0.6],
            [16, 3.2],
            [20, 15],
          ]),
        },
      },
      {
        id: 'road-major',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'motorway', 'trunk', 'primary', 'secondary'],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': c.majorRoad,
          'line-width': widthByZoom([
            [7, 0.8],
            [12, 2.6],
            [16, 7],
            [20, 24],
          ]),
        },
      },
      {
        id: 'rail',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'rail'],
        minzoom: 11,
        paint: {
          'line-color': c.rail,
          'line-dasharray': [3, 2],
          'line-width': widthByZoom([
            [11, 0.6],
            [18, 2.2],
          ]),
        },
      },

      // --- Boundaries ---------------------------------------------------------
      {
        id: 'boundary-country',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'boundary',
        filter: ['<=', 'admin_level', 2],
        paint: {
          'line-color': c.boundary,
          'line-width': widthByZoom([
            [3, 0.7],
            [10, 2],
          ]),
          'line-dasharray': [4, 2],
        },
      },
      {
        id: 'boundary-region',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'boundary',
        filter: ['all', ['>', 'admin_level', 2], ['<=', 'admin_level', 4]],
        minzoom: 5,
        paint: {
          'line-color': c.boundary,
          'line-opacity': 0.55,
          'line-width': 0.7,
          'line-dasharray': [3, 3],
        },
      },

      // --- Labels (always last) ----------------------------------------------
      ...labelLayers(c),
    ],
  } as StyleSpecification;
}

/**
 * Satellite imagery, on its own. A dark background sits under it so a tile that
 * hasn't arrived yet reads as "loading", not as a hole in the page.
 *
 * Theme-independent by design: a photograph of the ground looks the same at
 * midnight as at noon, and tinting it would only make it harder to read.
 */
export function satelliteStyle(): StyleSpecification {
  return {
    version: 8,
    name: 'Meridian — Satellite',
    sources: {
      satellite: {
        type: 'raster',
        tiles: [ESRI_IMAGERY],
        tileSize: 256,
        maxzoom: IMAGERY_MAX_ZOOM,
        attribution: IMAGERY_ATTRIBUTION,
      },
    },
    layers: [
      { id: 'background', type: 'background', paint: { 'background-color': '#0C1116' } },
      { id: 'satellite', type: 'raster', source: 'satellite' },
    ],
  };
}

/**
 * Satellite imagery with an OpenStreetMap overlay — the "hybrid" basemap, and
 * Meridian's default.
 *
 * Imagery alone is beautiful and nearly useless for a journal: you cannot tell
 * which valley you were in without a name on it. So the vector source draws a
 * deliberately thin overlay on top — arteries, minor roads once you're close
 * enough for them to mean something, administrative borders, and the full label
 * set. Roads are translucent warm white rather than opaque, so the ground stays
 * visible *through* the network instead of being covered by it.
 *
 * Like `satelliteStyle`, theme-independent.
 */
export function hybridStyle(): StyleSpecification {
  const c = IMAGERY;

  return {
    version: 8,
    name: 'Meridian — Satellite hybrid',
    glyphs: OPENFREEMAP_GLYPHS,
    sources: {
      satellite: {
        type: 'raster',
        tiles: [ESRI_IMAGERY],
        tileSize: 256,
        maxzoom: IMAGERY_MAX_ZOOM,
        attribution: IMAGERY_ATTRIBUTION,
      },
      openmaptiles: {
        type: 'vector',
        url: OPENFREEMAP_TILES,
        attribution: ATTRIBUTION,
      },
    },
    layers: [
      { id: 'background', type: 'background', paint: { 'background-color': '#0C1116' } },
      { id: 'satellite', type: 'raster', source: 'satellite' },

      // --- Borders, under the roads so a road never breaks for one ------------
      {
        id: 'hybrid-boundary',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'boundary',
        filter: ['<=', 'admin_level', 4],
        paint: {
          'line-color': '#F0D9B8',
          'line-opacity': 0.5,
          'line-dasharray': [4, 2],
          'line-width': widthByZoom([[3, 0.8], [10, 2]]),
        },
      },

      // --- Roads: thin and translucent, so the imagery reads through them -----
      {
        id: 'hybrid-road-minor',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'minor', 'service', 'tertiary'],
        minzoom: 13,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#FFFFFF',
          'line-opacity': 0.4,
          'line-width': widthByZoom([[13, 0.6], [16, 2], [20, 8]]),
        },
      },
      {
        id: 'hybrid-road-major',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'motorway', 'trunk', 'primary', 'secondary'],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#FFE0A8',
          'line-opacity': 0.7,
          'line-width': widthByZoom([[7, 0.8], [12, 2], [16, 5], [20, 16]]),
        },
      },

      // --- Labels (always last) ----------------------------------------------
      ...labelLayers(c, 1.8),
    ],
  } as StyleSpecification;
}

/**
 * The style to hand MapLibre, for the user's chosen basemap and the current theme.
 * `dark` comes from the resolved theme (system-following already applied), not the
 * raw setting, and only the parchment style uses it.
 *
 * An unrecognised id resolves to the default basemap rather than throwing — a
 * settings blob from a future (or corrupted) version still gets a map.
 */
export function mapStyleFor(style: MapStyleId, dark: boolean): StyleSpecification {
  switch (style) {
    case 'parchment':
      return parchmentStyle(dark);
    case 'osm':
      return rasterStyle();
    case 'satellite':
      return satelliteStyle();
    case 'hybrid':
    default:
      return hybridStyle();
  }
}

/** Is the dark theme currently applied? Read from the `<html>` class that
 *  `theme.ts` toggles, so it reflects `system` too. */
export function isDarkTheme(): boolean {
  return typeof document !== 'undefined' && document.documentElement.classList.contains('dark');
}

/**
 * What to draw instead when a style's VECTOR source can't be reached (offline, or
 * the tile host is down). Hybrid keeps its imagery and simply loses its labels;
 * anything else falls all the way back to raster OSM, which the service worker and
 * the offline region download both cache.
 */
export function vectorFallbackFor(style: MapStyleId): MapStyleId {
  return style === 'hybrid' ? 'satellite' : 'osm';
}

/** Human labels for the settings control, default first. Also the cycle order
 *  used by the command palette's basemap action. */
export const MAP_STYLE_OPTIONS: Array<{ id: MapStyleId; label: string; hint: string }> = [
  {
    id: 'hybrid',
    label: 'Hybrid',
    hint: 'Satellite imagery with roads, borders and place names over it. The most generally readable map anywhere in the world — the default.',
  },
  {
    id: 'satellite',
    label: 'Satellite',
    hint: 'The same imagery with no labels at all. The ground as it is, nothing written on it.',
  },
  {
    id: 'parchment',
    label: 'Parchment',
    hint: "Meridian's own cartography — warm cream land, terracotta roads, matched to the app. The only style that follows light/dark.",
  },
  {
    id: 'osm',
    label: 'Standard',
    hint: 'Plain OpenStreetMap tiles. The most reliable choice offline and on older phones.',
  },
];
